# Task 1 — PDF Preprocessing, Tokenization & Embeddings
### INFO-H-515 Big Data: Distributed Data Management and Scalable Analytics

In [3]:
# ── 1. Install dependencies (run once if packages are missing) ──────────────
%pip install pypdf sentence-transformers gensim scikit-learn pyarrow fastparquet

Collecting pypdf
  Downloading pypdf-6.11.0-py3-none-any.whl (338 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.8/338.8 KB 698.3 kB/s eta 0:00:0000:0100:01
Collecting sentence-transformers
  Downloading sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.0/488.0 KB 1.1 MB/s eta 0:00:00a 0:00:01
Collecting gensim
  Downloading gensim-4.4.0-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.6/27.6 MB 859.6 kB/s eta 0:00:000:0100:01
Requirement already satisfied: scikit-learn in /home/guest/anaconda3/lib/python3.9/site-packages (0.24.2)
Collecting pyarrow
  Downloading pyarrow-21.0.0-cp39-cp39-manylinux_2_28_x86_64.whl (42.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 MB 2.2 MB/s eta 0:00:0000:0100:01
Collecting fastparquet
  Downloading fastparquet-2024.11.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.5 MB/s eta 0:00:0000:0100:01
Collecting typing_extensions>=4.0
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 KB 2.2 MB/s eta 0:00:00
Collecting transformers<5.0.0,>=4.41.0
  Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 2.6 MB/s eta 0:00:0000:0100:01
Collecting torch>=1.11.0
  Downloading torch-2.8.0-cp39-cp39-manylinux_2_28_x86_64.whl (888.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 888.0/888.0 MB ? eta 0:00:00[36m0:00:0100:08�╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01�╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01�╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01�╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01�╸ 888.0/888.0 MB 3.0 MB/s eta 0:00:01
Collecting huggingface-hub>=0.20.0
  Downloading huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 625.2/625.2 KB 2.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: tqdm in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers) (4.62.3)
Requirement already satisfied: Pillow in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers) (8.4.0)
Requirement already satisfied: scipy in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers) (1.7.1)
Collecting smart_open>=1.8.1
  Downloading smart_open-7.5.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 KB 3.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.18.5 in /home/guest/anaconda3/lib/python3.9/site-packages (from gensim) (1.20.3)
Requirement already satisfied: joblib>=0.11 in /home/guest/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Collecting pandas>=1.5.0
  Downloading pandas-2.3.3-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 861.5 kB/s eta 0:00:000:0100:01
Collecting cramjam>=2.3
  Downloading cramjam-2.11.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 2.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: packaging in /home/guest/anaconda3/lib/python3.9/site-packages (from fastparquet) (21.0)
Requirement already satisfied: fsspec in /home/guest/anaconda3/lib/python3.9/site-packages (from fastparquet) (2021.8.1)
Collecting httpx<1,>=0.23.0
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 KB 3.1 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0)
Collecting hf-xet<2.0.0,>=1.4.2
  Downloading hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 2.8 MB/s eta 0:00:0000:0100:01
Collecting typer
  Downloading typer-0.23.2-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 KB 6.4 MB/s eta 0:00:00
Collecting fsspec
  Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.0/201.0 KB 4.5 MB/s eta 0:00:00a 0:00:01
Collecting filelock>=3.10.0
  Downloading filelock-3.19.1-py3-none-any.whl (15 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /home/guest/anaconda3/lib/python3.9/site-packages (from packaging->fastparquet) (3.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/guest/anaconda3/lib/python3.9/site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Collecting numpy>=1.18.5
  Downloading numpy-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 1.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2020.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from pandas>=1.5.0->fastparquet) (2021.3)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.3/349.3 KB 931.5 kB/s eta 0:00:0000:0100:01
Collecting numpy>=1.18.5
  Downloading numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 2.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: wrapt in /home/guest/anaconda3/lib/python3.9/site-packages (from smart_open>=1.8.1->gensim) (1.12.1)
Requirement already satisfied: jinja2 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers) (2.11.3)
Collecting nvidia-cusparselt-cu12==0.7.1
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 463.1 kB/s eta 0:00:0000:0100:04
Collecting nvidia-cublas-cu12==12.8.4.1
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB ? eta 0:00:00[36m0:00:0100:05�━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 508.5/594.3 MB 2.5 MB/s eta 0:00:34�━━━━━━━━━━━━━━━━━━━━━━━╸━━━━ 525.8/594.3 MB 1.9 MB/s eta 0:00:36
Collecting nvidia-cusolver-cu12==11.7.3.90
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 31.0 kB/s eta 0:00:0000:0100:03
Collecting nvidia-cufile-cu12==1.13.1.3

  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 530.4 kB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.9.90
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 1.3 MB/s eta 0:00:0000:0100:01�━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━ 26.5/63.6 MB 1.9 MB/s eta 0:00:20�━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 32.1/63.6 MB 2.4 MB/s eta 0:00:13
Collecting nvidia-nccl-cu12==2.27.3
  Downloading nvidia_nccl_cu12-2.27.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 MB ? eta 0:00:00[36m0:00:0100:04�━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 264.8/322.4 MB 2.6 MB/s eta 0:00:23�━━━━━━━━━━━━━━━━━━━━━━━━╺ 314.3/322.4 MB 2.7 MB/s eta 0:00:03�╸ 322.4/322.4 MB 3.3 MB/s eta 0:00:01�╸ 322.4/322.4 MB 3.3 MB/s eta 0:00:01
Collecting nvidia-cuda-nvrtc-cu12==12.8.93
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 1.7 MB/s eta 0:00:0000:0100:01m
Requirement already satisfied: networkx in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers) (2.6.3)
Collecting nvidia-nvjitlink-cu12==12.8.93
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 1.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-cupti-cu12==12.8.90
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 2.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.5.8.93
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB ? eta 0:00:00[36m0:00:0100:03�━━━━━╸━━━━━━━━━━━━━━━━━━━━━━ 123.4/288.2 MB 2.4 MB/s eta 0:01:10�╸ 288.2/288.2 MB 2.7 MB/s eta 0:00:01�╸ 288.2/288.2 MB 2.7 MB/s eta 0:00:01
Collecting triton==3.4.0
  Downloading triton-3.4.0-cp39-cp39-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.4/155.4 MB 765.1 kB/s eta 0:00:0000:0100:02�━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 75.3/155.4 MB 2.9 MB/s eta 0:00:28
Collecting nvidia-cufft-cu12==11.3.3.83
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 389.6 kB/s eta 0:00:0000:0100:02�╸ 193.1/193.1 MB 2.8 MB/s eta 0:00:01�╸ 193.1/193.1 MB 2.8 MB/s eta 0:00:01
Collecting sympy>=1.13.3
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 2.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu12==12.8.90
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 KB 1.8 MB/s eta 0:00:00a 0:00:01
Collecting nvidia-cudnn-cu12==9.10.2.21
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB ? eta 0:00:00[36m0:00:0100:08�━━━━━━━╸━━━━━━━━━━━━━━━━━━━━ 342.8/706.8 MB 3.0 MB/s eta 0:02:03��━━━━━━━━━━━━━━━━━━ 343.3/706.8 MB 2.9 MB/s eta 0:02:07━━━ 343.9/706.8 MB 2.7 MB/s eta 0:02:13�━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ 402.7/706.8 MB 3.2 MB/s eta 0:01:36�━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 416.6/706.8 MB 2.7 MB/s eta 0:01:49�━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 478.1/706.8 MB 3.2 MB/s eta 0:01:12�━━━━━━━━━━━━━━━━╺━━━━━━━━━━━ 496.6/706.8 MB 3.0 MB/s eta 0:01:09�━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 640.0/706.8 MB 2.9 MB/s eta 0:00:24�╸ 706.8/706.8 MB 3.0 MB/s eta 0:00:01━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 706.8/706.8 MB 3.0 MB/s eta 0:00:01.0 MB/s eta 0:00:01�╸ 706.8/706.8 MB 3.0 MB/s eta 0:00:01
Collecting nvidia-cuda-runtime-cu12==12.8.90
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 KB 2.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: importlib-metadata in /home/guest/anaconda3/lib/python3.9/site-packages (from triton==3.4.0->torch>=1.11.0->sentence-transformers) (4.8.1)
Requirement already satisfied: setuptools>=40.8.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from triton==3.4.0->torch>=1.11.0->sentence-transformers) (58.0.4)
Collecting safetensors>=0.4.3
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 KB 3.0 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: requests in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.26.0)
Collecting tokenizers<=0.23.0,>=0.22.0
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 2.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: regex!=2019.12.17 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2021.8.3)
Collecting huggingface-hub>=0.20.0
  Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 KB 2.8 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: certifi in /home/guest/anaconda3/lib/python3.9/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2021.10.8)
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 KB 991.2 kB/s eta 0:00:00 0:00:01
Requirement already satisfied: idna in /home/guest/anaconda3/lib/python3.9/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.2)
Requirement already satisfied: anyio in /home/guest/anaconda3/lib/python3.9/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2.2.0)

Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Requirement already satisfied: six>=1.5 in /home/guest/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/guest/anaconda3/lib/python3.9/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (1.1.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.7)
Collecting shellingham>=1.3.0
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich>=12.3.0
  Downloading rich-15.0.0-py3-none-any.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 KB 2.3 MB/s eta 0:00:00a 0:00:01
Collecting annotated-doc>=0.0.2
  Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Requirement already satisfied: click>=8.0.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.0.3)
Collecting pygments<3.0.0,>=2.13.0
  Downloading pygments-2.20.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.2 MB/s eta 0:00:00a 0:00:01
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 KB 3.3 MB/s eta 0:00:00
Requirement already satisfied: sniffio>=1.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: zipp>=0.5 in /home/guest/anaconda3/lib/python3.9/site-packages (from importlib-metadata->triton==3.4.0->torch>=1.11.0->sentence-transformers) (3.6.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: nvidia-cusparselt-cu12, tzdata, typing_extensions, sympy, smart_open, safetensors, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, hf-xet, fsspec, filelock, cramjam, triton, pypdf, pandas, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, gensim, fastparquet, transformers, torch, sentence-transformers
  Attempting uninstall: typing_extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
  Attempting uninstall: sympy
    Found existing installation: sympy 1.9
    Uninstalling sympy-1.9:
      Successfully uninstalled sympy-1.9
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2021.8.1
    Uninstalling fsspec-2021.8.1:
      Successfully uninstalled fsspec-2021.8.1
  Attempting uninstall: filelock
    Found existing installation: filelock 3.3.1
    Uninstalling filelock-3.3.1:
      Successfully uninstalled filelock-3.3.1
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.4
    Uninstalling pandas-1.3.4:
      Successfully uninstalled pandas-1.3.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.22.4 which is incompatible.
Successfully installed cramjam-2.11.0 fastparquet-2024.11.0 filelock-3.19.1 fsspec-2025.10.0 gensim-4.4.0 hf-xet-1.5.0 huggingface-hub-0.36.2 numpy-1.22.4 nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.3 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvtx-cu12-12.8.90 pandas-2.3.3 pyarrow-21.0.0 pypdf-6.11.0 safetensors-0.7.0 sentence-transformers-5.1.2 smart_open-7.5.0 sympy-1.14.0 tokenizers-0.22.2 torch-2.8.0 transformers-4.57.6 triton-3.4.0 typing_extensions-4.15.0 tzdata-2026.2
WARNING: You are using pip version 22.0.3; however, version 26.0.1 is available.
You should consider upgrading via the '/home/guest/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip uninstall -y transformers sentence-transformers
%pip install transformers==4.41.2 sentence-transformers==2.7.0

Found existing installation: transformers 4.57.6
Uninstalling transformers-4.57.6:
  Successfully uninstalled transformers-4.57.6
Found existing installation: sentence-transformers 5.1.2
Uninstalling sentence-transformers-5.1.2:
  Successfully uninstalled sentence-transformers-5.1.2
Note: you may need to restart the kernel to use updated packages.
Collecting transformers==4.41.2
  Downloading transformers-4.41.2-py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 3.8 MB/s eta 0:00:0000:0100:010m
Collecting sentence-transformers==2.7.0
  Downloading sentence_transformers-2.7.0-py3-none-any.whl (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 KB 5.6 MB/s eta 0:00:00
Collecting tokenizers<0.20,>=0.19
  Downloading tokenizers-0.19.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 5.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: packaging>=20.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (21.0)
Requirement already satisfied: filelock in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (1.22.4)
Requirement already satisfied: tqdm>=4.27 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (4.62.3)
Requirement already satisfied: regex!=2019.12.17 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (2021.8.3)
Requirement already satisfied: requests in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (2.26.0)
Requirement already satisfied: safetensors>=0.4.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (0.7.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (0.36.2)
Requirement already satisfied: pyyaml>=5.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from transformers==4.41.2) (6.0)
Requirement already satisfied: Pillow in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers==2.7.0) (8.4.0)
Requirement already satisfied: torch>=1.11.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers==2.7.0) (2.8.0)
Requirement already satisfied: scikit-learn in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers==2.7.0) (0.24.2)
Requirement already satisfied: scipy in /home/guest/anaconda3/lib/python3.9/site-packages (from sentence-transformers==2.7.0) (1.7.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/guest/anaconda3/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.2) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/guest/anaconda3/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.2) (1.5.0)
Requirement already satisfied: fsspec>=2023.5.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.2) (2025.10.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/guest/anaconda3/lib/python3.9/site-packages (from packaging>=20.0->transformers==4.41.2) (3.0.4)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.5.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (11.3.3.83)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (2.27.3)
Requirement already satisfied: jinja2 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (2.11.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (10.3.9.90)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.90)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (0.7.1)
Requirement already satisfied: networkx in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (2.6.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.93)
Requirement already satisfied: triton==3.4.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (3.4.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.4.1)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (11.7.3.90)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (12.8.93)
Requirement already satisfied: sympy>=1.13.3 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (1.14.0)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/guest/anaconda3/lib/python3.9/site-packages (from torch>=1.11.0->sentence-transformers==2.7.0) (9.10.2.21)
Requirement already satisfied: setuptools>=40.8.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from triton==3.4.0->torch>=1.11.0->sentence-transformers==2.7.0) (58.0.4)
Requirement already satisfied: importlib-metadata in /home/guest/anaconda3/lib/python3.9/site-packages (from triton==3.4.0->torch>=1.11.0->sentence-transformers==2.7.0) (4.8.1)
Requirement already satisfied: idna<4,>=2.5 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers==4.41.2) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers==4.41.2) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers==4.41.2) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/guest/anaconda3/lib/python3.9/site-packages (from requests->transformers==4.41.2) (1.26.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from scikit-learn->sentence-transformers==2.7.0) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /home/guest/anaconda3/lib/python3.9/site-packages (from scikit-learn->sentence-transformers==2.7.0) (1.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/guest/anaconda3/lib/python3.9/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==2.7.0) (1.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/guest/anaconda3/lib/python3.9/site-packages (from jinja2->torch>=1.11.0->sentence-transformers==2.7.0) (1.1.1)

Requirement already satisfied: zipp>=0.5 in /home/guest/anaconda3/lib/python3.9/site-packages (from importlib-metadata->triton==3.4.0->torch>=1.11.0->sentence-transformers==2.7.0) (3.6.0)
Installing collected packages: tokenizers, transformers, sentence-transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
Successfully installed sentence-transformers-2.7.0 tokenizers-0.19.1 transformers-4.41.2
WARNING: You are using pip version 22.0.3; however, version 26.0.1 is available.
You should consider upgrading via the '/home/guest/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [9]:
%pip install pyspark

Collecting pysparkNote: you may need to restart the kernel to use updated packages.

  Using cached pyspark-4.1.1.tar.gz (455.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting py4j<0.10.9.10,>=0.10.9.7 (from pyspark)
  Using cached py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Using cached py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (pyproject.toml): started
  Building wheel for pyspark (pyproject.toml): still running...
  Building wheel for pyspark (pyproject.toml): still running...
  Building wheel for pyspark (pyproject.toml): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-4.1.1-py2.py3-none-any.whl size=456008747 sha256=dfcb8eb7bb5c10470046d5db2aabaca804178a4bdb44f152d8b1464bf47e6b06
  Stored in directory: c:\users\bobby\appdata\local\pip\cache\wheels\16\33\a9\f8bff354a182417214933df74dace2a34b02c3e5643e8fac74
Successfully built pyspark
Installing collected packages: py4j, pyspark

   ---------------------------------------- 0/2 [py4j]
   ---------------------------------------- 0/2 [py4j]
   ---------------------------------------- 0/2 [py4j]
   ---------------------------------------- 0/2 [py4j]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   -------------------- ------------------- 1/2 [pyspark]
   ---------------------------------------- 2/2 [pyspark]

Successfully installed py4j-0.10.9.9 pyspark-4.1.1

In [2]:
# Imports
import os
import re
import time
import uuid
import json
import pickle
import logging
import unicodedata
from pathlib import Path
from typing import List, Dict

import numpy as np
import pandas as pd

from pypdf import PdfReader

from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField,
    StringType, IntegerType, FloatType, ArrayType,
)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline

from gensim.models import Word2Vec
from sentence_transformers import SentenceTransformer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
log = logging.getLogger("task1")

In [24]:
#Configuration


INPUT_DIR  = "/home/guest/shared/big_data/data/raw_pdfs"                        # folder containing PDFs
OUTPUT_DIR = "/home/guest/shared/big_data/data/processed/chunks_embeddings"     # Parquet output root

# Chunking
CHUNK_SIZE    = 300   # words per chunk  (spec: 200-500)
CHUNK_OVERLAP = 60    # overlap in words (spec: 10-30 % → 20 % of 300 = 60)

# Spark
PARALLELISM = 4

In [85]:
# TF-IDF
TFIDF_MAX_FEATURES = 10_000
TFIDF_SVD_DIM      = 256

# Word2Vec
WORD2VEC_DIM = 128

# SBERT  (all-MiniLM-L6-v2: 384-dim, fast, on-par with the spec baseline)
SBERT_MODEL = "all-MiniLM-L6-v2"

#to be changed later
EMBEDDING_STRATEGY = "sbert"

In [4]:
# Spark session 
def build_spark(parallelism: int = PARALLELISM) -> SparkSession:
    """
    Create (or reuse) a SparkSession.
    On a YARN / standalone cluster change .master() accordingly.
    """
    spark = (
        SparkSession.builder
        .appName("INFO-H515 Task1 Preprocessing & Embeddings")
        .config("spark.default.parallelism",    str(parallelism))
        .config("spark.sql.shuffle.partitions", str(parallelism))
        .config("spark.driver.memory",          "4g")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("WARN")
    return spark

In [5]:
spark = build_spark(PARALLELISM)
print(f"Spark version : {spark.version}")
print(f"App name      : {spark.sparkContext.appName}")
print(f"Master        : {spark.sparkContext.master}")
print(f"Parallelism   : {spark.sparkContext.defaultParallelism}")

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/14 18:04:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Spark version : 3.2.1
App name      : INFO-H515 Task1 Preprocessing & Embeddings
Master        : local[*]
Parallelism   : 4

In [6]:
#PDF extraction 
def extract_pdf_pages(pdf_path: str) -> List[Dict]:
    """
    Extract page-level raw text from one PDF using pypdf.

    Returns a list of dicts:
        { source_pdf: str, page_num: int (1-indexed), raw_text: str }
    """
    reader = PdfReader(pdf_path)
    pages  = []
    for page_num, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        pages.append({
            "source_pdf": os.path.basename(pdf_path),
            "page_num":   int(page_num),
            "raw_text":   text,
        })
    return pages

In [25]:
pdf_corpus=[]
for filename in os.listdir(INPUT_DIR):
    if filename.lower().endswith(".pdf"):
        pdf_path=os.path.join(INPUT_DIR, filename)
        pages=extract_pdf_pages(pdf_path)
        pdf_corpus.extend(pages)
print("Total extracted pages:", len(pdf_corpus))

2026-05-14 18:46:29,851 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-05-14 18:46:29,852 | WARNING | Ignoring wrong pointing object 39 0 (offset 0)
2026-05-14 18:46:29,853 | WARNING | Ignoring wrong pointing object 127 0 (offset 0)
2026-05-14 18:46:46,200 | WARNING | Ignoring wrong pointing object 7 0 (offset 0)
2026-05-14 18:46:46,201 | WARNING | Ignoring wrong pointing object 9 0 (offset 0)
2026-05-14 18:46:46,202 | WARNING | Ignoring wrong pointing object 11 0 (offset 0)
2026-05-14 18:46:46,203 | WARNING | Ignoring wrong pointing object 15 0 (offset 0)
2026-05-14 18:46:46,203 | WARNING | Ignoring wrong pointing object 17 0 (offset 0)
2026-05-14 18:46:46,204 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-05-14 18:46:46,204 | WARNING | Ignoring wrong pointing object 30 0 (offset 0)
2026-05-14 18:46:46,205 | WARNING | Ignoring wrong pointing object 37 0 (offset 0)
2026-05-14 18:46:46,206 | WARNING | Ignoring wrong pointing object 42 0 (offset 0)
2026-05-14 18:46:46,208 | WARNING | Ignoring wrong pointing object 52 0 (offset 0)
2026-05-14 18:46:46,208 | WARNING | Ignoring wrong pointing object 61 0 (offset 0)
2026-05-14 18:46:46,209 | WARNING | Ignoring wrong pointing object 71 0 (offset 0)
2026-05-14 18:46:46,209 | WARNING | Ignoring wrong pointing object 73 0 (offset 0)
2026-05-14 18:46:46,210 | WARNING | Ignoring wrong pointing object 79 0 (offset 0)
2026-05-14 18:46:46,211 | WARNING | Ignoring wrong pointing object 96 0 (offset 0)
2026-05-14 18:46:46,211 | WARNING | Ignoring wrong pointing object 100 0 (offset 0)
2026-05-14 18:46:46,212 | WARNING | Ignoring wrong pointing object 116 0 (offset 0)
2026-05-14 18:46:46,212 | WARNING | Ignoring wrong pointing object 128 0 (offset 0)
2026-05-14 18:46:46,213 | WARNING | Ignoring wrong pointing object 145 0 (offset 0)
2026-05-14 18:46:46,214 | WARNING | Ignoring wrong pointing object 147 0 (offset 0)
2026-05-14 18:46:46,214 | WARNING | Ignoring wrong pointing object 152 0 (offset 0)
2026-05-14 18:46:46,215 | WARNING | Ignoring wrong pointing object 165 0 (offset 0)
2026-05-14 18:46:46,215 | WARNING | Ignoring wrong pointing object 171 0 (offset 0)
2026-05-14 18:46:46,216 | WARNING | Ignoring wrong pointing object 174 0 (offset 0)
2026-05-14 18:46:46,216 | WARNING | Ignoring wrong pointing object 176 0 (offset 0)
2026-05-14 18:46:46,217 | WARNING | Ignoring wrong pointing object 178 0 (offset 0)
2026-05-14 18:46:46,218 | WARNING | Ignoring wrong pointing object 182 0 (offset 0)
2026-05-14 18:46:46,219 | WARNING | Ignoring wrong pointing object 216 0 (offset 0)
2026-05-14 18:46:46,220 | WARNING | Ignoring wrong pointing object 226 0 (offset 0)
2026-05-14 18:46:46,221 | WARNING | Ignoring wrong pointing object 228 0 (offset 0)
2026-05-14 18:46:46,221 | WARNING | Ignoring wrong pointing object 232 0 (offset 0)
2026-05-14 18:46:46,222 | WARNING | Ignoring wrong pointing object 234 0 (offset 0)
2026-05-14 18:46:46,222 | WARNING | Ignoring wrong pointing object 267 0 (offset 0)
2026-05-14 18:46:46,223 | WARNING | Ignoring wrong pointing object 363 0 (offset 0)
2026-05-14 18:46:46,224 | WARNING | Ignoring wrong pointing object 369 0 (offset 0)
2026-05-14 18:46:46,224 | WARNING | Ignoring wrong pointing object 372 0 (offset 0)
2026-05-14 18:46:46,225 | WARNING | Ignoring wrong pointing object 374 0 (offset 0)
2026-05-14 18:46:46,225 | WARNING | Ignoring wrong pointing object 376 0 (offset 0)
2026-05-14 18:46:46,226 | WARNING | Ignoring wrong pointing object 378 0 (offset 0)
2026-05-14 18:46:46,226 | WARNING | Ignoring wrong pointing object 428 0 (offset 0)
2026-05-14 18:46:46,227 | WARNING | Ignoring wrong pointing object 454 0 (offset 0)
2026-05-14 18:46:46,228 | WARNING | Ignoring wrong pointing object 604 0 (offset 0)
2026-05-14 18:46:46,228 | WARNING | Ignoring wrong pointing object 616 0 (offset 0)
2026-05-14 18:46:46,229 | WARNING | Ignoring wrong pointing object 801 0 (offset 0)
2026-05-14 18:46:46,230 | WARNING | Ignoring wrong pointing object 900 0 (offset 0)
2026-05-14 18:46:46,231 | WARNING | Ignoring wrong pointing object 902 0 (offset 0)
2026-05-14 18:46:46,232 | WARNING | Ignoring wrong pointing object 904 0 (offset 0)
2026-05-14 18:46:54,099 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-05-14 18:46:54,099 | WARNING | Ignoring wrong pointing object 56 0 (offset 0)
2026-05-14 18:46:54,100 | WARNING | Ignoring wrong pointing object 58 0 (offset 0)
2026-05-14 18:46:54,101 | WARNING | Ignoring wrong pointing object 72 0 (offset 0)

Total extracted pages: 1662

In [28]:
pdf_corpus_df= pd.DataFrame(pdf_corpus)

In [40]:
pdf_corpus_df_sorted=pdf_corpus_df.sort_values(
    by="raw_text",
    key=lambda col: col.str.split().str.len(),
    ascending=False
)
#we transform the pdf_corpus into a dataframe to easily vizualize the contents of our different
#pages and get insights on how to clean our pages.
#just via this table, we can see that we have empty pages

In [41]:
pdf_corpus_df_sorted

,source_pdf,page_num,raw_text
1023,a_TowardScalableSystemsForBigDataAnalytics.pdf,35,H. Hu et al.: Toward Scalable Systems for Big ...
1020,a_TowardScalableSystemsForBigDataAnalytics.pdf,32,H. Hu et al.: Toward Scalable Systems for Big ...
1022,a_TowardScalableSystemsForBigDataAnalytics.pdf,34,H. Hu et al.: Toward Scalable Systems for Big ...
1021,a_TowardScalableSystemsForBigDataAnalytics.pdf,33,H. Hu et al.: Toward Scalable Systems for Big ...
1024,a_TowardScalableSystemsForBigDataAnalytics.pdf,36,H. Hu et al.: Toward Scalable Systems for Big ...
...,...,...,...
1266,Intro_DL_H515_2026.pdf,38,38\n
871,"a_Big Data, Data Mining, and Machine Learning ...",268,www.it-ebooks.info
627,"a_Big Data, Data Mining, and Machine Learning ...",24,www.it-ebooks.info
10,1-intro.pdf,11,
57,1-intro.pdf,58,

In [45]:
pdf_corpus_df_sorted.loc[1023]['raw_text']#we will Clean PDF text by removing references, strange characters,
# broken formatting, and extra spaces while keeping meaningful content for RAG retrieval.the text below is
#an example with ccommon issue when extracting contents from pdfs.

'H. Hu et al.: Toward Scalable Systems for Big Data Analytics\n[218] W. Hu, N. Xie, L. Li, X. Zeng, and S. Maybank, ‘‘A survey on visual\ncontent-based video indexing and retrieval,’’ IEEE Trans. Syst., Man,\nCybern. C, Appl. Rev., vol. 41, no. 6, pp. 797–819, Nov. 2011.\n[219] X. Li, S. Lin, S. Y an, and D. Xu, ‘‘Discriminant locally linear embedding\nwith high-order tensor data,’’ IEEE Trans. Syst., Man, Cybern. B, Cybern. ,\nvol. 38, no. 2, pp. 342–352, Apr. 2008.\n[220] X. Li and Y . Pang, ‘‘Deterministic column-based matrix decomposition,’’\nIEEE Trans. Knowl. Data Eng. , vol. 22, no. 1, pp. 145–149, Jan. 2010.\n[221] X. Li, Y . Pang, and Y . Y uan, ‘‘L1-norm-based 2DPCA,’’ IEEE Trans.\nSyst., Man, Cybern. B Cybern. , vol. 40, no. 4, pp. 1170–1175, Apr. 2010.\n[222] Y .-J. Park and K.-N. Chang, ‘‘Individual and group behavior-based\ncustomer proﬁle model for personalized product recommendation,’’Expert\nSyst. Appl., vol. 36, no. 2, pp. 1932–1939, 2009.\n[223] L. M. de Campos, J. M. Fernández-Luna, J. F. Huete, and\nM. A. Rueda-Morales, ‘‘Combining content-based and collaborative\nrecommendations: A hybrid approach based on bayesian networks,’’ Int.\nJ. Approx. Reason., vol. 51, no. 7, pp. 785–799, 2010.\n[224] Y .-G. Jiang et al. , ‘‘Columbia-UCF TRECvid2010 multimedia event\ndetection: Combining multiple modalities, contextual concepts, and tem-\nporal matching,’’ in Proc. Nat. Inst. Standards Technol. (NIST) TRECvid\nWorkshop, vol. 2. 2010, p. 6.\n[225] Z. Ma, Y . Y ang, Y . Cai, N. Sebe, and A. G. Hauptmann, ‘‘Knowledge\nadaptation for ad hoc multimedia event detection with few exemplars,’’\nin Proc. 20th Assoc. Comput. Mach. (ACM) Int. Conf. Multimedia , 2012,\npp. 469–478.\n[226] J. E. Hirsch, ‘‘An index to quantify an individual’s scientiﬁc research\noutput,’’ Proc. Nat. Acad. Sci. United States Amer . , vol. 102, no. 46,\np. 16569, 2005.\n[227] D. J. Watts, Six Degrees: The Science of a Connected Age. New Y ork, NY ,\nUSA: Norton, 2004.\n[228] C. C. Aggarwal, An Introduction to Social Network Data Analytics .\nBerlin, Germany: Springer-V erlag, 2011.\n[229] S. Scellato, A. Noulas, and C. Mascolo, ‘‘Exploiting place features\nin link prediction on location-based social networks,’’ in Proc. 17th\nAssoc. Comput. Mach. (ACM) Special Interest Group Knowl. Discov-\nery Data (SIGKDD) Int. Conf. Knowl. Discovery Data Mining , 2011,\npp. 1046–1054.\n[230] A. Ninagawa and K. Eguchi, ‘‘Link prediction using probabilistic group\nmodels of network structure,’’ inProc. Assoc. Comput. Mach. (ACM) Symp.\nAppl. Comput., 2010, pp. 1115–1116.\n[231] D. M. Dunlavy, T. G. Kolda, and E. Acar, ‘‘Temporal link prediction using\nmatrix and tensor factorizations,’’ ACM Trans. Knowl. Discovery Data ,\nvol. 5, no. 2, pp. 10:1–10:27, 2011.\n[232] J. Leskovec, K. J. Lang, and M. Mahoney, ‘‘Empirical comparison of\nalgorithms for network community detection,’’ in Proc. 19th Int. Conf.\nWorld Wide Web, 2010, pp. 631–640.\n[233] N. Du, B. Wu, X. Pei, B. Wang, and L. Xu, ‘‘Community detection in\nlarge-scale social networks,’’ in Proc. 9th WebKDD 1st SNA-KDD Work-\nshop Web Mining Soc. Netw. Anal., 2007, pp. 16–25.\n[234] S. Garg, T. Gupta, N. Carlsson, and A. Mahanti, ‘‘Evolution of an online\nsocial aggregation network: An empirical study,’’ in Proc. 9th Assoc.\nComput. Mach. (ACM) SIGCOMM Conf. Internet Meas. Conf. , 2009,\npp. 315–321.\n[235] M. Allamanis, S. Scellato, and C. Mascolo, ‘‘Evolution\nof a location-based online social network: Analysis and models,’’ in\nProc. Assoc. Comput. Mach. (ACM) Conf. Internet Meas. Conf. , 2012,\npp. 145–158.\n[236] N. Z. Gong et al. , ‘‘Evolution of social-attribute networks:\nMeasurements, modeling, and implications using google+,’’ in Proc.\nAssoc. Comput. Mach. (ACM) Conf. Internet Meas. Conf. , 2012,\npp. 131–144.\n[237] E. Zheleva, H. Sharara, and L. Getoor, ‘‘Co-evolution of social\nand afﬁliation networks,’’ in Proc. 15th Assoc. Comput. Mach.\n(ACM) SIGKDD Int. Conf. Knowl. Discovery Data Mining , 2009,\npp. 1007–1016.\n[238] J. Tang, J. Sun, C. Wang, and Z. Y ang, ‘‘Social inﬂuence anal-\nysis in large-scale networks,’’ in Proc. 15th Assoc. Comput. Mach.\n(ACM) SIGKDD Int. Conf. Knowl. Discovery Data Mining , 2009,\npp. 807–816.\n[239] Y . Li, W. Chen, Y . Wang, and Z.-L. Zhang, ‘‘Inﬂuence diffusion dynamics\nand inﬂuence maximization in social networks with friend and foe relation-\nships,’’ in Proc. 6th Assoc. Comput. Mach. (ACM) Int. Conf. Web Search\nData Mining, 2013, pp. 657–666.\n[240] T. Lappas, K. Liu, and E. Terzi, ‘‘Finding a team of experts in social\nnetworks,’’ inProc. 15th Assoc. Comput. Mach. (ACM) SIGKDD Int. Conf.\nKnowl. Discovery Data Mining , 2009, pp. 467–476.\n[241] T. Zhang, A. Popescul, and B. Dom, ‘‘Linear prediction models with\ngraph regularization for web-page categorization,’’ in Proc. 12th Assoc.\nComput. Mach. (ACM) SIGKDD Int. Conf. Knowl. Discovery Data Mining,\n2006, pp. 821–826.\n[242] Y . Zhou, H. Cheng, and J. X. Y u, ‘‘Graph clustering based on\nstructural/attribute similarities,’’ Proc. VLDB Endowment , vol. 2, no. 1,\npp. 718–729, 2009.\n[243] W. Dai, Y . Chen, G.-R. Xue, Q. Y ang, and Y . Y u, ‘‘Translated learning:\nTransfer learning across different feature spaces,’’ in Proc. Adv. Neural\nInform. Process. Syst. (NIPS) , 2008, pp. 353–360.\n[244] M. Rabbath, P . Sandhaus, and S. Boll, ‘‘Multimedia retrieval in social\nnetworks for photo book creation,’’ in Proc. 1st Assoc. Comput. Mach.\n(ACM) Int. Conf. Multimedia Retr ., 2011, pp. 72:1–72:2.\n[245] S. Shridhar, M. Lakhanpuria, A. Charak, A. Gupta, and S. Shridhar,\n‘‘Snair: A framework for personalised recommendations based on social\nnetwork analysis,’’ in Proc. 5th Int. Workshop Location-Based Soc. Netw.,\n2012, pp. 55–61.\n[246] S. Maniu and B. Cautis, ‘‘Taagle: Efﬁcient, personalized search in\ncollaborative tagging networks,’’ in Proc. Assoc. Comput. Mach. (ACM)\nSIGMOD Int. Conf. Manag. Data , 2012, pp. 661–664.\n[247] H. Hu, J. Huang, H. Zhao, Y . Wen, C. W. Chen, and T.-S. Chua, ‘‘Social\ntv analytics: A novel paradigm to transform tv watching experience,’’ in\nProc. 5th Assoc. Comput. Mach. (ACM) Multimedia Syst. Conf. , 2014,\npp. 172–175.\n[248] H. Hu, Y . Wen, H. Luan, T.-S. Chua, and X. Li, ‘‘Towards\nmulti-screen social tv with geo-aware social sense,’’ IEEE Multimedia, to\nbe published.\n[249] H. Zhang, Z. Zhang, and H. Dai, ‘‘Gossip-based information spreading\nin mobile networks,’’ IEEE Trans. Wireless Commun. , vol. 12, no. 11,\npp. 5918–5928, Nov. 2013.\n[250] H. Zhang, Z. Zhang, and H. Dai, ‘‘Mobile conductance and\ngossip-based information spreading in mobile networks,’’ in IEEE\nInt. Symp. Inf. Theory Proc. (ISIT) , Jul. 2013, pp. 824–828.\n[251] H. Zhang, Y . Huang, Z. Zhang, and H. Dai. (2014). Mobile\nconductance in sparse networks and mobility-connectivity tradeoff.\nin Proc. IEEE Int. Symp. Inf. Theory (ISIT) [Online]. Available:\nhttp://www4.ncsu.edu/?hdai/ISIT2014-HZ.pdf\n[252] Cisco Syst., Inc., ‘‘Cisco visual networking index: Global mobile data\ntrafﬁc forecast update,’’ Cisco Syst., Inc., San Jose, CA, USA, Cisco\nTech. Rep. 2012-2017, 2013.\n[253] J. Han, J.-G. Lee, H. Gonzalez, and X. Li, ‘‘Mining massive RFID,\ntrajectory, and trafﬁc data sets,’’ in Proc. 14th ACM SIGKDD Int. Conf.\nKnowl. Discovery Data Mining (KDD) , 2008.\n[254] E. Wu, Y . Diao, and S. Rizvi, ‘‘High-performance complex event\nprocessing over streams,’’ in Proc. Assoc. Comput. Mach. (ACM)\nSIGMOD Int. Conf. Manag. Data , 2006, pp. 407–418.\n[255] M. K. Garg, D.-J. Kim, D. S. Turaga, and B. Prabhakaran, ‘‘Multimodal\nanalysis of body sensor network data streams for real-time healthcare,’’ in\nProc. Int. Conf. Multimedia Inform. Retr ., 2010, pp. 469–478.\n[256] Y . Park and J. Ghosh, ‘‘A probabilistic imputation framework for predic-\ntive analysis using variably aggregated, multi-source healthcare data,’’ in\nProc. 2nd Assoc. Comput. Mach. (ACM) SIGHIT Int. Health Inform. Symp.,\n2012, pp. 445–454.\n[257] T. Gunarathne, T.-L. Wu, J. Qiu, and G. Fox, ‘‘Cloud computing\nparadigms for pleasingly parallel biomedical applications,’’ in Proc. 19th\nAssoc. Comput. Mach. (ACM) Int. Symp. High Perform. Distrib. Comput. ,\n2010, pp. 460–469.\n[258] Y . Bu, B. Howe, M. Balazinska, and M. D. Ernst, ‘‘Haloop: Efﬁcient\niterative data processing on large clusters,’’Proc. VLDB Endowment, vol. 3,\nnos. 1–2, pp. 285–296, 2010.\n[259] J. Ekanayake et al. , ‘‘Twister: A runtime for iterative mapreduce,’’ in\nProc. 19th Assoc. Comput. Mach. (ACM) Int. Symp. High Perform. Distrib.\nComput., 2010, pp. 810–818.\n[260] D. Logothetis and K. Y ocum, ‘‘Ad-hoc data processing in the cloud,’’\nProc. VLDB Endowment, vol. 1, no. 2, pp. 1472–1475, 2008.\n[261] T. Condie, N. Conway, P . Alvaro, J. M. Hellerstein, K. Elmeleegy, and\nR. Sears, ‘‘Mapreduce online,’’ inProc. 7th USENIX Conf. Netw. Syst. Des.\nImplement., 2010, p. 21.\n[262] B. Li, E. Mazur, Y . Diao, A. McGregor, and P . Shenoy, ‘‘A platform for\nscalable one-pass analytics using mapreduce,’’ in Proc. Assoc. Comput.\nMach. (ACM) SIGMOD Int. Conf. Manag. Data , 2011, pp. 985–996.\n686 VOLUME 2, 2014'

In [46]:
# Text cleaning 
def clean_text(text: str) -> str:
    """
    Apply cleaning rules that address the most
    common PDF extraction.

    Rules (in order)
    ----------------
    1.  Unicode NFKC normalisation — resolves ligatures, half-width chars, etc.
    2.  Remove URLs and e-mail addresses (not useful for retrieval).
    3.  Remove browser-style timestamps  e.g. "4/16/26, 9:03 AM".
    4.  Remove page counters            e.g. "- 3 / 7 -", "9/9".
    5.  Re-join hyphenated line-breaks  e.g. "dis-\ntrubuted" → "distributed".
    6.  Collapse all remaining newlines into a single space.
    7.  Normalise Unicode punctuation to ASCII equivalents.
    8.  Strip non-printable control characters.
    9.  Truncate at reference/bibliography headers (irrelevant for retrieval).
    10. Collapse runs of whitespace to a single space.
    """
    if not text:
        return ""

    # 1. Unicode normalisation
    text = unicodedata.normalize("NFKC", text)

    # 2. URLs and e-mails
    text = re.sub(r"https?://\S+|www\.\S+",              " ", text)
    text = re.sub(r"\b[\w\.-]+@[\w\.-]+\.\w+\b",   " ", text)

    # 3. Browser timestamps
    text = re.sub(
        r"\b\d{1,2}/\d{1,2}/\d{2,4},?\s*\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)\b",
        " ", text,
    )

    # 4. Page counters
    text = re.sub(r"\b-?\s*\d+\s*/\s*\d+\s*-?\b", " ", text)

    # 5. Hyphenated line-breaks
    text = re.sub(r"(\w)-\s*\n\s*(\w)", r"\1\2", text)

    # 6. Remaining newlines → space
    text = re.sub(r"\s*\n\s*", " ", text)

    # 7. Unicode punctuation normalisation
    text = (
        text.replace("\u2013", "-").replace("\u2014", "-")
            .replace("\u2018", "'").replace("\u2019", "'")
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u00a0", " ")
    )

    # 8. Control characters
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", " ", text)

    # 9. Truncate at bibliography / references section header
    for marker in [r"\bReferences\b", r"\bBibliography\b",
                   r"\bWorks Cited\b", r"\bFurther Reading\b"]:
        m = re.search(marker, text, flags=re.IGNORECASE)
        if m:
            text = text[: m.start()]
            break

    # 10. Whitespace collapse
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [47]:
# Empty-page filter 
def is_empty_page(text: str,
                  min_words: int         = 20,
                  min_alpha_ratio: float = 0.50) -> bool:
    """
    Return True when a page carries so little useful text that chunking it
    would produce noisy, low-quality chunks.

    Criteria (all must pass for the page to be kept):
    * At least `min_words` whitespace-delimited tokens.
    * At least `min_alpha_ratio` of non-space characters are alphabetic
      (filters pages that are mostly numbers, symbols, or formulas).
    * At least 5 distinct word types (filters repetitive boilerplate).
    """
    if not text or not text.strip():
        return True

    words = text.strip().split()
    if len(words) < min_words:
        return True

    alpha_chars = sum(c.isalpha() for c in text)
    total_chars = sum(not c.isspace() for c in text)
    if total_chars == 0 or alpha_chars / total_chars < min_alpha_ratio:
        return True

    if len(set(words)) < 5:
        return True

    return False

In [49]:
cleaned_pages=[]
for page in pdf_corpus:
    cleaned= clean_text(page["raw_text"])
    if not is_empty_page(cleaned):
        cleaned_pages.append({
            "source_pdf":page["source_pdf"],
            "page_num": page["page_num"],
            "clean_text": cleaned,
            "word_count": len(cleaned.split())     
        })
print("pages before filtering:",len(pdf_corpus))
print("pages after filtering:", len(cleaned_pages))

pages before filtering: 1662
pages after filtering: 1397

In [50]:
# Chunking with metadata
def chunk_page_text(
    source_pdf: str,
    page_num:   int,
    text:       str,
    chunk_size: int = CHUNK_SIZE,
    overlap:    int = CHUNK_OVERLAP,
    min_chunk_words: int = 50,
) -> List[Dict]:
    """
    Split one cleaned page into overlapping, fixed-size word chunks.

    Design choice
    ----------------
    chunk_size = 300 words
        A 300-word chunk maps to roughly 400 sub-word tokens, which fits
        within SBERT's 512-token limit and within a typical LLM
        context window entry.  Going below 200 words risks splitting
        definitions; going above 500 words approaches the model limit.

    overlap = 60 words  (20 % of chunk_size)
        The overlap window reduces the probability that a definition, formula,
        or worked example is split right at a boundary.  A 10-30 % overlap is
        the range specified by the project; so, 20 % is a good default.

    Metadata stored per chunk:
        id            – UUID for globally unique identification
        source_pdf    – file name of the originating PDF
        page_num      – 1-indexed page number
        chunk_id      – composite key  <pdf>_p<page>_c<chunk>
        start_word    – index of the first word in the original page token list
        end_word      – index of the last word  (exclusive end)
        chunk_text    – the raw text of the chunk
        chunk_word_count – word count 
    """
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive.")
    if overlap < 0 or overlap >= chunk_size:
        raise ValueError("overlap must satisfy 0 <= overlap < chunk_size.")

    words       = text.split()
    step        = chunk_size - overlap
    chunks      = []
    chunk_index = 0

    for start in range(0, len(words), step):
        end         = min(start + chunk_size, len(words))
        chunk_words = words[start:end]

        if len(chunk_words) < min_chunk_words:
            # Skip tail fragments that are too short to be informative
            continue

        chunks.append({
            "id":              str(uuid.uuid4()),
            "source_pdf":      source_pdf,
            "page_num":        int(page_num),
            "chunk_id":        f"{source_pdf}_p{page_num:03d}_c{chunk_index:03d}",
            "start_word":      int(start),
            "end_word":        int(end),
            "chunk_text":      " ".join(chunk_words),
            "chunk_word_count": int(len(chunk_words)),
        })
        chunk_index += 1

    return chunks

In [54]:
chunks=[]
for page in cleaned_pages:
    chunk=chunk_page_text(page["source_pdf"], page["page_num"],page['clean_text'],CHUNK_SIZE, CHUNK_OVERLAP)
    chunks.extend(chunk)
print("number of cleaned pages:", len(cleaned_pages))
print("number of chunks:", len(chunks))

number of cleaned pages: 1397
number of chunks: 1872

In [58]:
chunks[1871]

{'id': 'ad3b6933-4261-451e-9509-5fd56bd4bb96',
 'source_pdf': 'Transformer Explainer_ LLM Transformer Model Visually Explained.pdf',
 'page_num': 9,
 'chunk_id': 'Transformer Explainer_ LLM Transformer Model Visually Explained.pdf_p009_c000',
 'start_word': 0,
 'end_word': 174,
 'chunk_text': "How is Transformer Explainer Implemented? Transformer Explainer features a live GPT-2 (small) model running directly in the browser. This model is derived from the PyTorch implementation of GPT by Andrej Karpathy's nanoGPTproject and has been converted to ONNX Runtime for seamless in-browser execution. Theinterface is built using JavaScript, with Svelte as a front-end framework and D3.js for creatingdynamic visualizations. Numerical values are updated live following the user input. Who developed the Transformer Explainer? Transformer Explainer was created by Aeree Cho, Grace C. Kim, Alexander Karpekov, AlecHelbling, Jay Wang, Seongmin Lee, Benjamin Hoover, and Polo Chau at the Georgia Institute ofTechnology. Polo Club of Data Science @ Georgia Tech Transfo rm ers Explained V isually: Learn H o w LLM Transfo rm er M o de Transfo rm ers Explained V isually: Learn H o w LLM Transfo rm er M o de Watch on TRANSFORMER EXPLAINER Temperature 0.8 tion empowers users to easily Try the examples while GPT-2 model is being downloaded (600MB) Sampling Top-k Top-p k=5 Transformer Explainer: LLM Transformer Model Visually Explained",
 'chunk_word_count': 174}

In [62]:
pd.DataFrame(chunks)[pd.DataFrame(chunks)['chunk_word_count']>=300].sort_values(by=['source_pdf','page_num'])#to see if we chunked as we 
#wanted, with overlap=60.

,id,source_pdf,page_num,chunk_id,start_word,end_word,chunk_text,chunk_word_count
330,3143454a-a2c7-48b8-9e7f-ab0fef6eb302,9780521192248_excerpt.pdf,1,9780521192248_excerpt.pdf_p001_c000,0,300,CHAPTER 1 Scaling Up Machine Learning: Introdu...,300
333,5c265e24-66e9-421d-b743-248688738697,9780521192248_excerpt.pdf,3,9780521192248_excerpt.pdf_p003_c000,0,300,1.2 reasons for scaling up machine learning 3 ...,300
334,efc491ea-a035-4d6a-8dfc-368c19889efc,9780521192248_excerpt.pdf,3,9780521192248_excerpt.pdf_p003_c001,240,540,i wixi ) so as to predict the label. The most ...,300
336,b1ebae79-811c-4a72-a6c2-8ca99aecefb4,9780521192248_excerpt.pdf,4,9780521192248_excerpt.pdf_p004_c000,0,300,4 1 scaling up machine learning: introduction ...,300
338,b38a85df-09fe-4f7c-9547-ae58442a55c3,9780521192248_excerpt.pdf,5,9780521192248_excerpt.pdf_p005_c000,0,300,1.2 reasons for scaling up machine learning 5 ...,300
...,...,...,...,...,...,...,...,...
1805,f2d83422-6116-4c7d-9ea9-b45174c457e7,stats.pdf,4,stats.pdf_p004_c000,0,300,= 1 Wn (wnxn + Wn−1μn−1) (50) = 1 Wn (wnxn + (...,300
1807,336d0b11-fd10-4661-a3ed-901f3f8ad01a,stats.pdf,5,stats.pdf_p005_c000,0,300,sample to change as the set of samples changes...,300
1809,83302bad-46e7-4ec5-a258-0d2f5bd06cf7,stats.pdf,6,stats.pdf_p006_c000,0,300,= En(x2) − μ2 n (86) = En(x2) − En(x)2 (87) Th...,300
1811,2610e58f-6464-438b-bff0-ac213f710a43,stats.pdf,7,stats.pdf_p007_c000,0,300,"= [ μn − μn−1] (wn,n[xn − μn−1] + (Wn − wn,n)E...",300
1813,ee318dd5-e61c-42e8-a52b-c07b17030728,stats.pdf,8,stats.pdf_p008_c000,0,300,= a3μn−3 + a2(1 − a)xn−2 + a(1 − a)xn−1 + (1 −...,300

In [63]:
# Distributed ingestion via PySpark RDD
def list_pdf_paths(input_dir: str = INPUT_DIR) -> List[str]:
    """Recursively collect all .pdf / .PDF paths under input_dir."""
    return sorted(
        str(p) for p in Path(input_dir).rglob("*")
        if p.is_file() and p.suffix.lower() == ".pdf"
    )


def pdf_to_chunks(
    spark:       SparkSession,
    input_dir:   str = INPUT_DIR,
    parallelism: int = PARALLELISM,
    chunk_size:  int = CHUNK_SIZE,
    overlap:     int = CHUNK_OVERLAP,
):
    """
    Distributed ingestion pipeline.

    Architecture
    ------------
    1. Collect all PDF file paths o.
    2. Parallelize the path list across `parallelism` Spark partitions.
    3. Each executor independently:
       a. reads pages with pypdf
       b. cleans each page
       c. filters empty pages
       d. chunks the remaining pages
    4. flatMap flattens partition outputs into a single RDD of chunk dicts.

    chunk_size and overlap are broadcast to avoid repeated serialisation
    of the closure on every task dispatch.
    """
    pdf_paths = list_pdf_paths(input_dir)
    if not pdf_paths:
        raise FileNotFoundError(f"No PDFs found in {input_dir!r}")

    log.info("Found %d PDF(s) in %s", len(pdf_paths), input_dir)

    sc = spark.sparkContext
    cs = sc.broadcast(chunk_size)
    ov = sc.broadcast(overlap)

    def process_pdf(path: str) -> List[Dict]:
        out = []
        try:
            for page in extract_pdf_pages(path):
                text = clean_text(page["raw_text"])
                if is_empty_page(text):
                    continue
                out.extend(
                    chunk_page_text(
                        source_pdf = page["source_pdf"],
                        page_num   = page["page_num"],
                        text       = text,
                        chunk_size = cs.value,
                        overlap    = ov.value,
                    )
                )
        except Exception as exc:
            # Isolate failures to individual PDFs; the rest of the job continues.
            print(f"WARNING: could not process {path}: {exc}")
        return out

    rdd   = sc.parallelize(pdf_paths, numSlices=parallelism).flatMap(process_pdf)
    count = rdd.count()
    log.info("Total chunks produced: %d", count)
    return rdd

In [64]:
# Run distributed ingestion and inspect the results
chunk_rdd = pdf_to_chunks(
    spark       = spark,
    input_dir   = INPUT_DIR,
    parallelism = PARALLELISM,
    chunk_size  = CHUNK_SIZE,
    overlap     = CHUNK_OVERLAP,
)

# Collect to driver for embedding (sklearn / gensim / SBERT run on the driver)
chunks = chunk_rdd.collect()

# Summary statistics
_sources = {}
for ch in chunks:
    _sources.setdefault(ch["source_pdf"], []).append(ch["chunk_word_count"])

print(f"{'PDF':<40} {'pages (chunks)':<16} {'avg words/chunk'}")
print("-" * 70)
for pdf, wcs in sorted(_sources.items()):
    print(f"{pdf:<40} {len(wcs):<16} {sum(wcs)/len(wcs):.0f}")
print("-" * 70)
print(f"{'TOTAL':<40} {len(chunks)}")

2026-05-14 20:12:38,353 | INFO | Found 29 PDF(s) in /home/guest/shared/big_data/data/raw_pdfs
Ignoring wrong pointing object 27 0 (offset 0)                      (0 + 4) / 4]
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 165 0 (offset 0)
Ignoring wrong pointing object 171 0 (offset 0)
Ignoring wrong pointing object 174 0 (offset 0)
Ignoring wrong pointing object 176 0 (offset 0)
Ignoring wrong pointing object 178 0 (offset 0)
Ignoring wrong pointing object 182 0 (offset 0)
Ignoring wrong pointing object 216 0 (offset 0)
Ignoring wrong pointing object 226 0 (offset 0)
Ignoring wrong pointing object 228 0 (offset 0)
Ignoring wrong pointing object 232 0 (offset 0)
Ignoring wrong pointing object 234 0 (offset 0)
Ignoring wrong pointing object 267 0 (offset 0)
Ignoring wrong pointing object 363 0 (offset 0)
Ignoring wrong pointing object 369 0 (offset 0)
Ignoring wrong pointing object 372 0 (offset 0)
Ignoring wrong pointing object 374 0 (offset 0)
Ignoring wrong pointing object 376 0 (offset 0)
Ignoring wrong pointing object 378 0 (offset 0)
Ignoring wrong pointing object 428 0 (offset 0)
Ignoring wrong pointing object 454 0 (offset 0)
Ignoring wrong pointing object 604 0 (offset 0)
Ignoring wrong pointing object 616 0 (offset 0)
Ignoring wrong pointing object 801 0 (offset 0)
Ignoring wrong pointing object 900 0 (offset 0)
Ignoring wrong pointing object 902 0 (offset 0)
Ignoring wrong pointing object 904 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)=======>              (3 + 1) / 4]
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)
2026-05-14 20:13:28,567 | INFO | Total chunks produced: 1872
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)                       (0 + 4) / 4]
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 165 0 (offset 0)
Ignoring wrong pointing object 171 0 (offset 0)
Ignoring wrong pointing object 174 0 (offset 0)
Ignoring wrong pointing object 176 0 (offset 0)
Ignoring wrong pointing object 178 0 (offset 0)
Ignoring wrong pointing object 182 0 (offset 0)
Ignoring wrong pointing object 216 0 (offset 0)
Ignoring wrong pointing object 226 0 (offset 0)
Ignoring wrong pointing object 228 0 (offset 0)
Ignoring wrong pointing object 232 0 (offset 0)
Ignoring wrong pointing object 234 0 (offset 0)
Ignoring wrong pointing object 267 0 (offset 0)
Ignoring wrong pointing object 363 0 (offset 0)
Ignoring wrong pointing object 369 0 (offset 0)
Ignoring wrong pointing object 372 0 (offset 0)
Ignoring wrong pointing object 374 0 (offset 0)
Ignoring wrong pointing object 376 0 (offset 0)
Ignoring wrong pointing object 378 0 (offset 0)
Ignoring wrong pointing object 428 0 (offset 0)
Ignoring wrong pointing object 454 0 (offset 0)
Ignoring wrong pointing object 604 0 (offset 0)
Ignoring wrong pointing object 616 0 (offset 0)
Ignoring wrong pointing object 801 0 (offset 0)
Ignoring wrong pointing object 900 0 (offset 0)
Ignoring wrong pointing object 902 0 (offset 0)
Ignoring wrong pointing object 904 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)=======>              (3 + 1) / 4]
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)

PDF                                      pages (chunks)   avg words/chunk
----------------------------------------------------------------------
1-intro.pdf                              35               86
2-spark.pdf                              45               89
3-stream_proc.pdf                        76               79
4-stream_algos.pdf                       54               78
5-nosql.pdf                              62               102
6-parallel.pdf                           58               96
9780521192248_excerpt.pdf                20               261
A Neural Network Playground.pdf          3                205
Finding Similar Items.pdf                132              247
Gama_ACMCS_AdaptationCD_accepted (1).pdf 117              246
Gama_ACMCS_AdaptationCD_accepted.pdf     117              246
Intro_DL_H515_2026.pdf                   4                62
LLM Lecture 2.pdf                        44               107
Recommender-Systems-[Netflix].pdf        22               241
Scalability COST.pdf                     16               251
Stream Algos.pdf                         41               250
Transformer Explainer_ LLM Transformer Model Visually Explained.pdf 16               201
a_Big Data, Data Mining, and Machine Learning ( PDFDrive.com )-min.pdf 425              217
a_ScalableMachineLearningAlgorithmsforBigDataAnalytics-ChallengesandOpportunities.pdf 27               202
a_TowardScalableSystemsForBigDataAnalytics.pdf 134              266
a_the-big-book-of-machine-learning-use-cases.pdf 109              212
intro.pdf                                29               83
kdd00.pdf                                38               271
mr.pdf                                   63               98
msrtr-2013-2.pdf                         41               245
online-1998.pdf                          65               217
online.pdf                               32               86
recommend.pdf                            31               112
stats.pdf                                16               211
----------------------------------------------------------------------
TOTAL                                    1872

In [67]:
chunk_df = spark.createDataFrame(chunk_rdd)

In [69]:
chunk_df.select(
    "source_pdf",
    "page_num",
    "chunk_word_count",
    "start_word",
    "end_word"
    
).show(10, truncate=False)

+-----------+--------+----------------+----------+--------+
|source_pdf |page_num|chunk_word_count|start_word|end_word|
+-----------+--------+----------------+----------+--------+
|1-intro.pdf|9       |87              |0         |87      |
|1-intro.pdf|10      |72              |0         |72      |
|1-intro.pdf|12      |83              |0         |83      |
|1-intro.pdf|14      |116             |0         |116     |
|1-intro.pdf|15      |67              |0         |67      |
|1-intro.pdf|16      |95              |0         |95      |
|1-intro.pdf|17      |92              |0         |92      |
|1-intro.pdf|18      |81              |0         |81      |
|1-intro.pdf|26      |80              |0         |80      |
|1-intro.pdf|27      |87              |0         |87      |
+-----------+--------+----------------+----------+--------+
only showing top 10 rows

In [70]:
#TF-IDF embedding 
def embed_tfidf(
    chunks:       List[Dict],
    max_features: int = TFIDF_MAX_FEATURES,
    svd_dim:      int = TFIDF_SVD_DIM,
    min_df:       int = 2,
    output_dir:   str = OUTPUT_DIR,
) -> List[Dict]:
    """
    Fit a TF-IDF + TruncatedSVD (LSA) pipeline on the full chunk corpus
    and attach a dense embedding to every chunk.


    """
    if not chunks:
        raise ValueError("No chunks provided to embed_tfidf().")

    texts = [c["chunk_text"] for c in chunks]

    tfidf = TfidfVectorizer(
        max_features = max_features,
        sublinear_tf = True,        # apply 1+log(tf) scaling
        ngram_range  = (1, 2),      # unigrams + bigrams
        min_df       = min_df,      # ignore very rare terms
        stop_words   = "english",
    )

    log.info("Fitting TF-IDF  max_features=%s  min_df=%s", max_features, min_df)
    X_tfidf    = tfidf.fit_transform(texts)
    vocab_size = X_tfidf.shape[1]

    if vocab_size < 2:
        raise ValueError(f"TF-IDF vocabulary too small ({vocab_size}). "
                         "Lower min_df or add more documents.")

    n_components = min(svd_dim, vocab_size - 1)
    svd = TruncatedSVD(n_components=n_components, random_state=42)

    log.info("Fitting TruncatedSVD  n_components=%d", n_components)
    vectors            = svd.fit_transform(X_tfidf).astype(np.float32)
    explained_variance = float(svd.explained_variance_ratio_.sum())

    pipeline = Pipeline([("tfidf", tfidf), ("svd", svd)])

    for chunk, vec in zip(chunks, vectors):
        chunk["embedding"]          = vec.tolist()
        chunk["embedding_strategy"] = "tfidf"
        chunk["embedding_dim"]      = int(n_components)

    os.makedirs(output_dir, exist_ok=True)
    pipeline_path = os.path.join(output_dir, "tfidf_pipeline.pkl")
    with open(pipeline_path, "wb") as fh:
        pickle.dump(pipeline, fh)

    log.info(
        "TF-IDF pipeline saved | vocab=%d | svd_dim=%d | explained_var=%.3f",
        vocab_size, n_components, explained_variance,
    )
    return chunks

In [72]:
import copy
_tfidf_chunks = embed_tfidf(
    copy.deepcopy(chunks),    # deep copy so we can re-embed with other strategies
    max_features = TFIDF_MAX_FEATURES,
    svd_dim      = TFIDF_SVD_DIM,
    output_dir   = OUTPUT_DIR,
)

_sample = _tfidf_chunks[0]
print(f"strategy       : {_sample['embedding_strategy']}")
print(f"embedding_dim  : {_sample['embedding_dim']}")
print(f"embedding[:8]  : {[round(x,4) for x in _sample['embedding'][:8]]}")
print()
_dims = [c['embedding_dim'] for c in _tfidf_chunks]
print(f"All chunks have consistent embedding dim: {len(set(_dims)) == 1}  (dim = {_dims[0]})")

2026-05-14 20:37:25,395 | INFO | Fitting TF-IDF  max_features=10000  min_df=2
2026-05-14 20:37:27,355 | INFO | Fitting TruncatedSVD  n_components=256
2026-05-14 20:37:30,225 | INFO | TF-IDF pipeline saved | vocab=10000 | svd_dim=256 | explained_var=0.466

strategy       : tfidf
embedding_dim  : 256
embedding[:8]  : [0.1126, -0.006, 0.024, -0.0393, 0.0442, -0.0358, 0.0304, -0.0099]

All chunks have consistent embedding dim: True  (dim = 256)

In [73]:
# Word2Vec embedding 
def embed_word2vec(
    chunks:     List[Dict],
    dim:        int = WORD2VEC_DIM,
    output_dir: str = OUTPUT_DIR,
) -> List[Dict]:
    """
    Train a Word2Vec (skip-gram) model on the chunk corpus, then represent
    each chunk as the mean of its in-vocabulary word vectors.

    Why Word2Vec?
    -------------
    Word2Vec captures local syntactic and semantic similarity better than
    TF-IDF (e.g. 'distributed' ≈ 'parallelised') while being much lighter
    than full sentence transformers.

    OOV handling: chunks where every token falls outside the trained
    vocabulary receive a zero vector (logged as a warning).

    
    """
    from gensim.models import Word2Vec as GensimW2V

    if not chunks:
        raise ValueError("No chunks provided to embed_word2vec().")

    sentences     = [c["chunk_text"].lower().split() for c in chunks]
    non_empty     = [s for s in sentences if s]
    if not non_empty:
        raise ValueError("No tokens found for Word2Vec training.")

    log.info("Training Word2Vec on %d sentences  vector_size=%d", len(non_empty), dim)
    model = GensimW2V(
        sentences   = non_empty,
        vector_size = dim,
        window      = 5,
        min_count   = 2,
        workers     = 4,
        epochs      = 10,
        seed        = 42,
    )

    zero_vec  = np.zeros(dim, dtype=np.float32)
    oov_count = 0

    for chunk, sent in zip(chunks, sentences):
        vecs = [model.wv[w] for w in sent if w in model.wv]
        if vecs:
            vec = np.mean(vecs, axis=0).astype(np.float32)
        else:
            vec = zero_vec.copy()
            oov_count += 1
        chunk["embedding"]          = vec.tolist()
        chunk["embedding_strategy"] = "word2vec"
        chunk["embedding_dim"]      = int(dim)

    if oov_count:
        log.warning(
            "%d/%d chunks contained only OOV tokens — zero vector assigned.",
            oov_count, len(chunks),
        )

    os.makedirs(output_dir, exist_ok=True)
    model_path = os.path.join(output_dir, "word2vec.model")
    model.save(model_path)
    log.info("Word2Vec model saved to %s", model_path)
    return chunks

In [74]:
_w2v_chunks = embed_word2vec(
    copy.deepcopy(chunks),
    dim        = WORD2VEC_DIM,
    output_dir = OUTPUT_DIR,
)

_sample = _w2v_chunks[0]
print(f"strategy       : {_sample['embedding_strategy']}")
print(f"embedding_dim  : {_sample['embedding_dim']}")
print(f"embedding[:8]  : {[round(x,4) for x in _sample['embedding'][:8]]}")
print()
# Count OOV (zero) vectors
_oov = sum(1 for c in _w2v_chunks if all(v == 0.0 for v in c['embedding']))
print(f"OOV (zero) chunks: {_oov} / {len(_w2v_chunks)}")

2026-05-14 20:40:26,695 | INFO | Training Word2Vec on 1872 sentences  vector_size=128
2026-05-14 20:40:26,708 | INFO | collecting all words and their counts
2026-05-14 20:40:26,711 | INFO | PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2026-05-14 20:40:26,750 | INFO | collected 32914 word types from a corpus of 361934 raw words and 1872 sentences
2026-05-14 20:40:26,753 | INFO | Creating a fresh vocabulary
2026-05-14 20:40:26,815 | INFO | Word2Vec lifecycle event {'msg': 'effective_min_count=2 retains 18115 unique words (55.04% of original 32914, drops 14799)', 'datetime': '2026-05-14T20:40:26.809651', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'prepare_vocab'}
2026-05-14 20:40:26,818 | INFO | Word2Vec lifecycle event {'msg': 'effective_min_count=2 leaves 347135 word corpus (95.91% of original 361934, drops 14799)', 'datetime': '2026-05-14T20:40:26.818215', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'prepare_vocab'}
2026-05-14 20:40:26,888 | INFO | deleting the raw counts dictionary of 32914 items
2026-05-14 20:40:26,889 | INFO | sample=0.001 downsamples 32 most-common words
2026-05-14 20:40:26,890 | INFO | Word2Vec lifecycle event {'msg': 'downsampling leaves estimated 281795.3047099991 word corpus (81.2%% of prior 347135)', 'datetime': '2026-05-14T20:40:26.890310', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'prepare_vocab'}
2026-05-14 20:40:27,020 | INFO | estimated required memory for 18115 words and 128 dimensions: 27607260 bytes
2026-05-14 20:40:27,021 | INFO | resetting layer weights
2026-05-14 20:40:27,049 | INFO | Word2Vec lifecycle event {'update': False, 'trim_rule': 'None', 'datetime': '2026-05-14T20:40:27.049609', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'build_vocab'}
2026-05-14 20:40:27,053 | INFO | Word2Vec lifecycle event {'msg': 'training model with 4 workers on 18115 vocabulary and 128 features, using sg=0 hs=0 sample=0.001 negative=5 window=5 shrink_windows=True', 'datetime': '2026-05-14T20:40:27.053535', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'train'}
2026-05-14 20:40:27,248 | INFO | EPOCH 0: training on 361934 raw words (281759 effective words) took 0.2s, 1750390 effective words/s
2026-05-14 20:40:27,398 | INFO | EPOCH 1: training on 361934 raw words (281869 effective words) took 0.1s, 2081549 effective words/s
2026-05-14 20:40:27,549 | INFO | EPOCH 2: training on 361934 raw words (281925 effective words) took 0.1s, 1953053 effective words/s
2026-05-14 20:40:27,690 | INFO | EPOCH 3: training on 361934 raw words (281730 effective words) took 0.1s, 2109878 effective words/s
2026-05-14 20:40:27,838 | INFO | EPOCH 4: training on 361934 raw words (281776 effective words) took 0.1s, 2003514 effective words/s
2026-05-14 20:40:27,986 | INFO | EPOCH 5: training on 361934 raw words (281799 effective words) took 0.1s, 1986169 effective words/s
2026-05-14 20:40:28,134 | INFO | EPOCH 6: training on 361934 raw words (281686 effective words) took 0.1s, 1982819 effective words/s
2026-05-14 20:40:28,285 | INFO | EPOCH 7: training on 361934 raw words (281755 effective words) took 0.1s, 1919248 effective words/s
2026-05-14 20:40:28,427 | INFO | EPOCH 8: training on 361934 raw words (281777 effective words) took 0.1s, 2093892 effective words/s
2026-05-14 20:40:28,571 | INFO | EPOCH 9: training on 361934 raw words (281932 effective words) took 0.1s, 2060789 effective words/s
2026-05-14 20:40:28,571 | INFO | Word2Vec lifecycle event {'msg': 'training on 3619340 raw words (2818008 effective words) took 1.5s, 1857714 effective words/s', 'datetime': '2026-05-14T20:40:28.571833', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'train'}
2026-05-14 20:40:28,574 | INFO | Word2Vec lifecycle event {'params': 'Word2Vec<vocab=18115, vector_size=128, alpha=0.025>', 'datetime': '2026-05-14T20:40:28.574007', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'created'}
2026-05-14 20:40:29,253 | INFO | Word2Vec lifecycle event {'fname_or_handle': '/home/guest/shared/big_data/data/processed/chunks_embeddings/word2vec.model', 'separately': 'None', 'sep_limit': 10485760, 'ignore': frozenset(), 'datetime': '2026-05-14T20:40:29.252948', 'gensim': '4.4.0', 'python': '3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]', 'platform': 'Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'event': 'saving'}
2026-05-14 20:40:29,264 | INFO | not storing attribute cum_table
2026-05-14 20:40:29,408 | INFO | saved /home/guest/shared/big_data/data/processed/chunks_embeddings/word2vec.model
2026-05-14 20:40:29,409 | INFO | Word2Vec model saved to /home/guest/shared/big_data/data/processed/chunks_embeddings/word2vec.model

strategy       : word2vec
embedding_dim  : 128
embedding[:8]  : [0.2588, 0.3098, 0.2996, -0.4088, 0.0515, 0.1353, -0.201, 0.1491]

OOV (zero) chunks: 0 / 1872

In [75]:
#SBERT embedding 
def embed_sbert(
    chunks:     List[Dict],
    model_name: str = SBERT_MODEL,
    batch_size: int = 64,
    output_dir: str = OUTPUT_DIR,
) -> List[Dict]:
    """
    Encode all chunks with a pre-trained SentenceTransformer model.

    Why SBERT?
    ----------
    Models from the sentence-transformers library (all-MiniLM-L6-v2 chosen
    here) produce contextual, dense embeddings that capture long-range
    semantic relationships — outperforming both TF-IDF and Word2Vec on
    semantic retrieval benchmarks. .

    Note on distribution
    --------------------
    SentenceTransformer.encode() is a batched GPU/CPU call that is already
    internally parallelised. We run it on the Spark driver after a
    .collect() — calling it from within an executor would cause OOM errors
    and serialisation issues with the tokeniser.

    .
    """
    from sentence_transformers import SentenceTransformer

    if not chunks:
        raise ValueError("No chunks provided to embed_sbert().")

    texts = [c["chunk_text"] for c in chunks]

    log.info("Loading SBERT model: %s", model_name)
    model = SentenceTransformer(model_name)

    log.info("Encoding %d chunks  batch_size=%d", len(texts), batch_size)
    t0      = time.time()
    vectors = model.encode(
        texts,
        batch_size        = batch_size,
        show_progress_bar = True,
        convert_to_numpy  = True,
    ).astype(np.float32)
    elapsed     = time.time() - t0
    emb_dim     = int(vectors.shape[1])

    log.info("SBERT done in %.1fs  embedding_dim=%d", elapsed, emb_dim)

    for chunk, vec in zip(chunks, vectors):
        chunk["embedding"]          = vec.tolist()
        chunk["embedding_strategy"] = "sbert"
        chunk["embedding_dim"]      = emb_dim

    os.makedirs(output_dir, exist_ok=True)
    config_path = os.path.join(output_dir, "sbert_config.json")
    with open(config_path, "w") as fh:
        json.dump({"model_name": model_name, "embedding_dim": emb_dim,
                   "batch_size": batch_size}, fh, indent=2)

    log.info("SBERT config saved to %s", config_path)
    return chunks

In [76]:
_sbert_chunks = embed_sbert(
    copy.deepcopy(chunks),
    model_name = SBERT_MODEL,
    output_dir = OUTPUT_DIR,
)

_sample = _sbert_chunks[0]
print(f"strategy       : {_sample['embedding_strategy']}")
print(f"embedding_dim  : {_sample['embedding_dim']}")
print(f"embedding[:8]  : {[round(x,4) for x in _sample['embedding'][:8]]}")

# Quick cosine similarity between first two chunks as sanity check
def _cosine(a, b):
    a, b = np.array(a), np.array(b)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))

if len(_sbert_chunks) >= 2:
    sim = _cosine(_sbert_chunks[0]["embedding"], _sbert_chunks[1]["embedding"])
    print(f"\nCosine similarity (chunk 0, chunk 1): {sim:.4f}")

2026-05-14 20:43:23,247 | INFO | Loading SBERT model: all-MiniLM-L6-v2
2026-05-14 20:43:23,269 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/home/guest/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2026-05-14 20:43:50,831 | INFO | Use pytorch device_name: cpu
2026-05-14 20:43:50,846 | INFO | Encoding 1872 chunks  batch_size=64

Batches:   0%|          | 0/30 [00:00<?, ?it/s]

2026-05-14 20:45:33,057 | INFO | SBERT done in 102.2s  embedding_dim=384
2026-05-14 20:45:33,375 | INFO | SBERT config saved to /home/guest/shared/big_data/data/processed/chunks_embeddings/sbert_config.json

strategy       : sbert
embedding_dim  : 384
embedding[:8]  : [0.0079, -0.097, 0.0272, -0.0462, 0.0447, -0.0315, -0.0442, -0.0326]

Cosine similarity (chunk 0, chunk 1): 0.6609

In [77]:
# Parquet schema and storage 
# Schema matches the spec:
# [id, source_pdf, page_num, chunk_id, start_word, end_word,
#  chunk_text, embedding, embedding_strategy]
# plus chunk_word_count and embedding_dim.

CHUNK_SCHEMA = StructType([
    StructField("id",                 StringType(),           False),
    StructField("source_pdf",         StringType(),           False),
    StructField("page_num",           IntegerType(),          False),
    StructField("chunk_id",           StringType(),           False),
    StructField("start_word",         IntegerType(),          False),
    StructField("end_word",           IntegerType(),          False),
    StructField("chunk_text",         StringType(),           False),
    StructField("chunk_word_count",   IntegerType(),          False),
    StructField("embedding",          ArrayType(FloatType()), False),
    StructField("embedding_strategy", StringType(),           False),
    StructField("embedding_dim",      IntegerType(),          False),
])


def save_to_parquet(
    spark:      SparkSession,
    chunks:     List[Dict],
    output_dir: str = OUTPUT_DIR,
    strategy:   str = EMBEDDING_STRATEGY,
) -> None:
    """
    Persist embedded chunks as Parquet, partitioned by embedding strategy.

    The output path  <output_dir>/strategy=<name>  lets Task 2 load only
    the partitions it needs without reading unrelated strategies.

    """
    if not chunks:
        raise ValueError("No chunks to save.")

    os.makedirs(output_dir, exist_ok=True)
    df       = spark.createDataFrame(chunks, schema=CHUNK_SCHEMA)
    out_path = os.path.join(output_dir, f"strategy={strategy}")

    log.info("Writing %d rows → %s", df.count(), out_path)
    (
        df.repartition(PARALLELISM)
          .write
          .mode("overwrite")
          .parquet(out_path)
    )

    verify = spark.read.parquet(out_path)
    log.info(
        "Verification — rows=%d | schema=%s",
        verify.count(), verify.schema.simpleString(),
    )
    verify.show(5, truncate=90)

In [78]:
# save TF-IDF chunks 
save_to_parquet(
    spark      = spark,
    chunks     = _tfidf_chunks,
    output_dir = OUTPUT_DIR,
    strategy   = "tfidf",
)
print("Parquet files written to:", os.path.join(OUTPUT_DIR, "strategy=tfidf"))
print(sorted(Path(OUTPUT_DIR, "strategy=tfidf").glob("*.parquet")))

26/05/14 20:53:10 WARN TaskSetManager: Stage 5 contains a task of very large size (1461 KiB). The maximum recommended task size is 1000 KiB.
2026-05-14 20:53:11,699 | INFO | Writing 1872 rows → /home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf
26/05/14 20:53:13 WARN TaskSetManager: Stage 8 contains a task of very large size (1461 KiB). The maximum recommended task size is 1000 KiB.
2026-05-14 20:53:17,947 | INFO | Verification — rows=1872 | schema=struct<id:string,source_pdf:string,page_num:int,chunk_id:string,start_word:int,end_word:int,chunk_text:string,chunk_word_count:int,embedding:array<float>,embedding_strategy:string,embedding_dim:int>

+------------------------------------+-------------------------+--------+-----------------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
|                                  id|               source_pdf|page_num|                           chunk_id|start_word|end_word|                                                                                chunk_text|chunk_word_count|                                                                                 embedding|embedding_strategy|embedding_dim|
+------------------------------------+-------------------------+--------+-----------------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
|7392b2a2-0b59-4b92-a45f-febd4ffb3277|        3-stream_proc.pdf|      83|        3-stream_proc.pdf_p083_c000|         0|      51|STORM API Spout API p u b l i c i n t e r f a c e ISpout extends Serializable { void op...|              51|[0.024498144, 0.0045312797, -0.0061383517, -0.0062227086, 0.033699255, 0.072355814, -0....|             tfidf|          256|
|9a39abb2-f5bc-4a0a-a3ad-f8ce092d1150|       4-stream_algos.pdf|      49|       4-stream_algos.pdf_p049_c000|         0|      55|Distinct Counting: Attempt 1a S={} N=0 Whenever a person P enters the room: if P not in...|              55|[0.06448496, 0.047448684, -0.031047907, 0.019754618, -0.0118492525, -0.0046336357, 0.01...|             tfidf|          256|
|e1666382-2d60-40a0-b06a-5e25461e747e|Finding Similar Items.pdf|      17|Finding Similar Items.pdf_p017_c001|       240|     540|m rows of matrix M . Let S1 and S2 be the sets represented by two columns of M . Then t...|             300|[0.11884002, 0.009183942, -0.21689327, 0.2517365, 0.19070661, 0.012592565, -0.06392862,...|             tfidf|          256|
|2aac46ac-de92-4656-b0c0-054e2617eae9|              5-nosql.pdf|     116|              5-nosql.pdf_p116_c000|         0|     119|THE HISTORY OF CONSISTENT HASHING Paper by CS theoreticians from MIT that introduced CH...|             119|[0.093230516, 0.015188432, -0.004612732, -0.016745565, 0.058450192, 0.039826438, 0.0052...|             tfidf|          256|
|990b86c5-bd3d-4385-ae00-64950948df8b|        3-stream_proc.pdf|      96|        3-stream_proc.pdf_p096_c000|         0|      99|GUARANTEEING MESSAGE PROCESSING p u b l i c c l a s s SplitSentenceBolt implements IRic...|              99|[0.035912175, 0.025477136, -0.02931199, 0.011073043, 0.025772067, 0.07195469, -0.046931...|             tfidf|          256|
+------------------------------------+-------------------------+--------+-----------------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
only showing top 5 rows

Parquet files written to: /home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf
[PosixPath('/home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf/part-00000-6202a122-ffa5-4f56-8784-3c960bbbd203-c000.snappy.parquet'), PosixPath('/home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf/part-00001-6202a122-ffa5-4f56-8784-3c960bbbd203-c000.snappy.parquet'), PosixPath('/home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf/part-00002-6202a122-ffa5-4f56-8784-3c960bbbd203-c000.snappy.parquet'), PosixPath('/home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=tfidf/part-00003-6202a122-ffa5-4f56-8784-3c960bbbd203-c000.snappy.parquet')]

In [79]:
#Full pipeline 
EMBEDDING_DISPATCH = {
    "tfidf":    embed_tfidf,
    "word2vec": embed_word2vec,
    "sbert":    embed_sbert,
}


def run_pipeline(
    parallelism:        int = PARALLELISM,
    chunk_size:         int = CHUNK_SIZE,
    chunk_overlap:      int = CHUNK_OVERLAP,
    embedding_strategy: str = EMBEDDING_STRATEGY,
    input_dir:          str = INPUT_DIR,
    output_dir:         str = OUTPUT_DIR,
    **embedding_kwargs,
) -> List[Dict]:
    """
    End-to-end Task 1 pipeline.

    Steps
    -----
    1. Start / reuse Spark.
    2. Distributed PDF ingestion: path parallelisation + flatMap (PySpark RDD).
    3. Collect chunks to driver (required for sklearn / gensim / SBERT fit).
    4. Generate embeddings on driver.
    5. Persist as Parquet (HDFS or local FS).

    Parameters
    ----------
    parallelism        : Spark default parallelism and number of RDD partitions.
    chunk_size         : Number of words per chunk (200-500).
    chunk_overlap      : Overlap in words between consecutive chunks (10-30 %).
    embedding_strategy : One of 'tfidf', 'word2vec', 'sbert'.
    input_dir          : Directory containing the source PDF files.
    output_dir         : Root directory for Parquet output and model artefacts.
    **embedding_kwargs : Forwarded to the chosen embedding function
                         (e.g. max_features for TF-IDF).

    Returns
    -------
    List of embedded chunk dicts (also written to Parquet).
    """
    if embedding_strategy not in EMBEDDING_DISPATCH:
        raise ValueError(
            f"Unknown embedding_strategy {embedding_strategy!r}. "
            f"Choose from {list(EMBEDDING_DISPATCH)}."
        )

    t_start = time.time()
    spark   = build_spark(parallelism)

    # ── Step 1: distributed PDF ingestion 
    log.info("=== Step 1/4: Distributed PDF ingestion ===")
    chunk_rdd = pdf_to_chunks(spark, input_dir, parallelism, chunk_size, chunk_overlap)

    # ── Step 2: collect to driver 
    log.info("=== Step 2/4: Collecting chunks to driver ===")
    all_chunks = chunk_rdd.collect()
    n_pdfs     = len({c["source_pdf"] for c in all_chunks})
    log.info("Collected %d chunks from %d PDF(s)", len(all_chunks), n_pdfs)

    # ── Step 3: embed 
    log.info("=== Step 3/4: Embedding (strategy=%s) ===", embedding_strategy)
    embed_fn   = EMBEDDING_DISPATCH[embedding_strategy]
    all_chunks = embed_fn(all_chunks, output_dir=output_dir, **embedding_kwargs)

    # ── Step 4: persist
    log.info("=== Step 4/4: Persisting to Parquet ===")
    save_to_parquet(spark, all_chunks, output_dir, embedding_strategy)

    elapsed = time.time() - t_start
    log.info("=== Pipeline complete in %.1fs ===", elapsed)

    return all_chunks

In [86]:
# Adjust EMBEDDING_STRATEGY in the Configuration cell (cell 3) to switch
# between 'tfidf', 'word2vec', and 'sbert'.

chunks_out = run_pipeline(
    parallelism        = PARALLELISM,
    chunk_size         = CHUNK_SIZE,
    chunk_overlap      = CHUNK_OVERLAP,
    embedding_strategy = EMBEDDING_STRATEGY,
    input_dir          = INPUT_DIR,
    output_dir         = OUTPUT_DIR,
)

# Final summary 
print(f"\n{'='*60}")
print(f"  Pipeline summary")
print(f"{'='*60}")
print(f"  Total chunks produced : {len(chunks_out)}")
print(f"  Embedding strategy    : {chunks_out[0]['embedding_strategy']}")
print(f"  Embedding dimension   : {chunks_out[0]['embedding_dim']}")
print(f"  Output directory      : {OUTPUT_DIR}/strategy={EMBEDDING_STRATEGY}")

# Word count distribution
_wcs = [c["chunk_word_count"] for c in chunks_out]
print(f"  Chunk word count      : min={min(_wcs)}  mean={sum(_wcs)/len(_wcs):.0f}  max={max(_wcs)}")

# Unique PDFs
_pdfs = sorted({c["source_pdf"] for c in chunks_out})
print(f"  Source PDFs ({len(_pdfs)})      : {_pdfs}")
print(f"{'='*60}")

2026-05-14 21:11:57,911 | INFO | === Step 1/4: Distributed PDF ingestion ===
2026-05-14 21:11:57,996 | INFO | Found 29 PDF(s) in /home/guest/shared/big_data/data/raw_pdfs
Ignoring wrong pointing object 27 0 (offset 0)                      (0 + 4) / 4]
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 165 0 (offset 0)
Ignoring wrong pointing object 171 0 (offset 0)
Ignoring wrong pointing object 174 0 (offset 0)
Ignoring wrong pointing object 176 0 (offset 0)
Ignoring wrong pointing object 178 0 (offset 0)
Ignoring wrong pointing object 182 0 (offset 0)
Ignoring wrong pointing object 216 0 (offset 0)
Ignoring wrong pointing object 226 0 (offset 0)
Ignoring wrong pointing object 228 0 (offset 0)
Ignoring wrong pointing object 232 0 (offset 0)
Ignoring wrong pointing object 234 0 (offset 0)
Ignoring wrong pointing object 267 0 (offset 0)
Ignoring wrong pointing object 363 0 (offset 0)
Ignoring wrong pointing object 369 0 (offset 0)
Ignoring wrong pointing object 372 0 (offset 0)
Ignoring wrong pointing object 374 0 (offset 0)
Ignoring wrong pointing object 376 0 (offset 0)
Ignoring wrong pointing object 378 0 (offset 0)
Ignoring wrong pointing object 428 0 (offset 0)
Ignoring wrong pointing object 454 0 (offset 0)
Ignoring wrong pointing object 604 0 (offset 0)
Ignoring wrong pointing object 616 0 (offset 0)
Ignoring wrong pointing object 801 0 (offset 0)
Ignoring wrong pointing object 900 0 (offset 0)
Ignoring wrong pointing object 902 0 (offset 0)
Ignoring wrong pointing object 904 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)=======>              (3 + 1) / 4]
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)
2026-05-14 21:12:32,395 | INFO | Total chunks produced: 1872
2026-05-14 21:12:32,395 | INFO | === Step 2/4: Collecting chunks to driver ===
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 72 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)                       (0 + 4) / 4]
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 52 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 100 0 (offset 0)
Ignoring wrong pointing object 116 0 (offset 0)
Ignoring wrong pointing object 128 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 147 0 (offset 0)
Ignoring wrong pointing object 152 0 (offset 0)
Ignoring wrong pointing object 165 0 (offset 0)
Ignoring wrong pointing object 171 0 (offset 0)
Ignoring wrong pointing object 174 0 (offset 0)
Ignoring wrong pointing object 176 0 (offset 0)
Ignoring wrong pointing object 178 0 (offset 0)
Ignoring wrong pointing object 182 0 (offset 0)
Ignoring wrong pointing object 216 0 (offset 0)
Ignoring wrong pointing object 226 0 (offset 0)
Ignoring wrong pointing object 228 0 (offset 0)
Ignoring wrong pointing object 232 0 (offset 0)
Ignoring wrong pointing object 234 0 (offset 0)
Ignoring wrong pointing object 267 0 (offset 0)
Ignoring wrong pointing object 363 0 (offset 0)
Ignoring wrong pointing object 369 0 (offset 0)
Ignoring wrong pointing object 372 0 (offset 0)
Ignoring wrong pointing object 374 0 (offset 0)
Ignoring wrong pointing object 376 0 (offset 0)
Ignoring wrong pointing object 378 0 (offset 0)
Ignoring wrong pointing object 428 0 (offset 0)
Ignoring wrong pointing object 454 0 (offset 0)
Ignoring wrong pointing object 604 0 (offset 0)
Ignoring wrong pointing object 616 0 (offset 0)
Ignoring wrong pointing object 801 0 (offset 0)
Ignoring wrong pointing object 900 0 (offset 0)
Ignoring wrong pointing object 902 0 (offset 0)
Ignoring wrong pointing object 904 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)=======>              (3 + 1) / 4]
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 127 0 (offset 0)
2026-05-14 21:13:06,489 | INFO | Collected 1872 chunks from 29 PDF(s)
2026-05-14 21:13:06,490 | INFO | === Step 3/4: Embedding (strategy=sbert) ===
2026-05-14 21:13:06,492 | INFO | Loading SBERT model: all-MiniLM-L6-v2
2026-05-14 21:13:06,508 | INFO | Load pretrained SentenceTransformer: all-MiniLM-L6-v2
/home/guest/anaconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2026-05-14 21:13:10,857 | INFO | Use pytorch device_name: cpu
2026-05-14 21:13:10,873 | INFO | Encoding 1872 chunks  batch_size=64

Batches:   0%|          | 0/30 [00:00<?, ?it/s]

2026-05-14 21:14:44,778 | INFO | SBERT done in 93.9s  embedding_dim=384
2026-05-14 21:14:45,127 | INFO | SBERT config saved to /home/guest/shared/big_data/data/processed/chunks_embeddings/sbert_config.json
2026-05-14 21:14:45,150 | INFO | === Step 4/4: Persisting to Parquet ===
26/05/14 21:14:47 WARN TaskSetManager: Stage 44 contains a task of very large size (1988 KiB). The maximum recommended task size is 1000 KiB.
2026-05-14 21:14:49,112 | INFO | Writing 1872 rows → /home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=sbert
26/05/14 21:14:49 WARN TaskSetManager: Stage 47 contains a task of very large size (1988 KiB). The maximum recommended task size is 1000 KiB.
2026-05-14 21:14:55,071 | INFO | Verification — rows=1872 | schema=struct<id:string,source_pdf:string,page_num:int,chunk_id:string,start_word:int,end_word:int,chunk_text:string,chunk_word_count:int,embedding:array<float>,embedding_strategy:string,embedding_dim:int>
2026-05-14 21:14:55,424 | INFO | === Pipeline complete in 177.5s ===

+------------------------------------+-----------------+--------+---------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
|                                  id|       source_pdf|page_num|                   chunk_id|start_word|end_word|                                                                                chunk_text|chunk_word_count|                                                                                 embedding|embedding_strategy|embedding_dim|
+------------------------------------+-----------------+--------+---------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
|f56d1dc5-0b4c-43e9-a648-ac77b2c2bfbe|   6-parallel.pdf|      39|   6-parallel.pdf_p039_c000|         0|      50|BSP COST MODEL 20 Cost C of a computation consisting of S supersteps: C = S∑ i=1 (wi + ...|              50|[-0.07443472, 0.022728711, -0.012152525, 0.030108789, 0.025160143, 0.010033562, -0.0688...|             sbert|          384|
|f66459b9-5552-41a1-9a40-7f656fad81fc|3-stream_proc.pdf|      20|3-stream_proc.pdf_p020_c000|         0|      70|THE PROBLEM OF MUTABLE DATA ( ) Mutable data is corruptable. • Bugs will be deployed to...|              70|[-0.010071409, 0.045899317, 0.03662225, -0.032969203, -0.014409867, -0.12105242, -0.016...|             sbert|          384|
|0e9a5a3b-fcd3-4452-9aa2-265f27889be2|      5-nosql.pdf|      22|      5-nosql.pdf_p022_c000|         0|     232|TYPES OF NOSQL DATABASES Year System/Paper Scale to1000sPrimaryIndexSecondaryIndex Tran...|             232|[-0.0066832243, 0.024721045, -0.095348135, -0.013589178, -0.058454324, -0.0077383975, -...|             sbert|          384|
|3cd9aa09-a29c-4e3a-8867-15602060d54b|      5-nosql.pdf|      44|      5-nosql.pdf_p044_c000|         0|      79|2PC EXAMPLE ONE coordinator subordinate 1 subordinate 2 subordinate 3 (1) update reques...|              79|[-0.022005768, -0.0778898, -0.03755953, 0.10101098, -0.026513573, -0.038066126, 0.00683...|             sbert|          384|
|1f96af36-14ae-4a02-8d47-8704f9defacd|      5-nosql.pdf|      36|      5-nosql.pdf_p036_c000|         0|      84|CAP THEOREM • Conventional databases assume no partitioning - clusters were assumed to ...|              84|[-0.059165735, -0.008583408, -0.058901217, 0.071406, 0.06962353, -0.045116402, -0.04128...|             sbert|          384|
+------------------------------------+-----------------+--------+---------------------------+----------+--------+------------------------------------------------------------------------------------------+----------------+------------------------------------------------------------------------------------------+------------------+-------------+
only showing top 5 rows


============================================================
  Pipeline summary
============================================================
  Total chunks produced : 1872
  Embedding strategy    : sbert
  Embedding dimension   : 384
  Output directory      : /home/guest/shared/big_data/data/processed/chunks_embeddings/strategy=sbert
  Chunk word count      : min=50  mean=193  max=300
  Source PDFs (29)      : ['1-intro.pdf', '2-spark.pdf', '3-stream_proc.pdf', '4-stream_algos.pdf', '5-nosql.pdf', '6-parallel.pdf', '9780521192248_excerpt.pdf', 'A Neural Network Playground.pdf', 'Finding Similar Items.pdf', 'Gama_ACMCS_AdaptationCD_accepted (1).pdf', 'Gama_ACMCS_AdaptationCD_accepted.pdf', 'Intro_DL_H515_2026.pdf', 'LLM Lecture 2.pdf', 'Recommender-Systems-[Netflix].pdf', 'Scalability COST.pdf', 'Stream Algos.pdf', 'Transformer Explainer_ LLM Transformer Model Visually Explained.pdf', 'a_Big Data, Data Mining, and Machine Learning ( PDFDrive.com )-min.pdf', 'a_ScalableMachineLearningAlgorithmsforBigDataAnalytics-ChallengesandOpportunities.pdf', 'a_TowardScalableSystemsForBigDataAnalytics.pdf', 'a_the-big-book-of-machine-learning-use-cases.pdf', 'intro.pdf', 'kdd00.pdf', 'mr.pdf', 'msrtr-2013-2.pdf', 'online-1998.pdf', 'online.pdf', 'recommend.pdf', 'stats.pdf']
============================================================